### ISSUE TITLE
`chainHead_unstable_follow` withRuntime=false emits `stop` shortly after `initialized` 

### ISSUE THREAD

**Issue by voliva** [smol-dot/smoldot#1665]
I'm encountering an issue where `chainHead_unstable_follow` with `withRuntime = false` is not emitting events beyond the initial `initialized`. After a brief pause it emits `stop` terminating the subscription.

I'm using latest smoldot@2.0.20, polkadot-api and polkadot-spec.

I have forked @josepot's test repo to generate some logs that might help, with a simple reproduction case   https://github.com/voliva/smoldot-withRuntime-false-test/blob/main/src/main.ts

JSON-RPC messages: [wire-logs.txt](https://github.com/smol-dot/smoldot/files/14168632/wire-logs.txt)
smoldot logs: [smoldot-logs.txt](https://github.com/smol-dot/smoldot/files/14168637/smoldot-logs.txt)

By looking at smoldot's logs, it looks like it happens right after warp sync finishes, it triggers a `SyncServiceSubscriptionReset`

I'm happy to help investigate or provide more info

**Comment by tomaka** [comment]
This is intended behavior.

Subscribing causes smoldot to report the latest block that it knows is valid. Immediately after start-up, this is equal to the checkpoint in the chain spec.
Once smoldot connects to other nodes, it will download newer blocks. If these newer blocks are far ahead, then smoldot will emit a `stop` notification instead of trying to download every block in between the old and newer blocks.

**Comment by josepot** [comment]
> This is intended behavior.
> 
> Subscribing causes smoldot to report the latest block that it knows is valid. Immediately after start-up, this is equal to the checkpoint in the chain spec, or to the genesis block if there's no checkpoint.
> 
> Once smoldot connects to other nodes, it will download newer blocks. If these newer blocks are far ahead, then smoldot will emit a `stop` notification instead of trying to download every block in between the old and newer blocks.

I'm sure that I must be something in here, but this behaviour seems to be at odds with [what's described in this section of the spec](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#the-withruntime-parameter).

Doesn't it make more sense to report as the `finalizedBlockHash` of the `initialized` event the latest block that finalized block that smoldot has learned about after it has successfully connected to one of its peers? What's the point of reporting the latest checkpoint in the spec?

Isn't this like saying that smoldot doesn't offer proper support for using `chainHead_unstable_follow` with the `withRuntime` flag set to `false`? Which, by the way, it wouldn't be a big deal to us, since we only use it with the  `withRuntime` flag set to `true`.

**Comment by tomaka** [comment]
> this behaviour seems to be at odds with [what's described in this section of the spec](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#the-withruntime-parameter).

In which way?

> Doesn't it make more sense

In which way?

> What's the point of reporting the latest checkpoint in the spec?

You get to know the latest block that smoldot knows is valid, which is better than not knowing any block at all.

> Which, by the way, it wouldn't be a big deal to us, since we only use it with the withRuntime flag set to true.

Then I'm not sure what the issue is?

**Comment by voliva** [comment]
I would expect `chainHead_unstable_follow` to behave similarly when withRuntime is on or off. However, currently withRuntime=true does emit all of the events (as I expect from a subscription), whereas withRuntime=false it only emits `intialized` followed by `stop`.

If the behaviour is expected to be this different, wouldn't it make more sense to split withRuntime=false into a separate method? e.g. `chainHead_unstable_getLastValidBlock`

**Comment by tomaka** [comment]
It *does* behave similarly. It just doesn't in that specific situation you've tried.

The same behaviour can happen (`initialized` then `stop`) with `withRuntime: true` if smoldot manages to download and compile the runtime before performing a warp sync, which is something that can realistically happen.
Additionally, if the checkpoint in the chain spec is close to the head of the chain, then no `stop` will be generated.

In addition to this, this only concerns smoldot/light clients. When it comes to Substrate or full nodes in general, the `withRuntime` parameter has absolutely no influence.

**Comment by voliva** [comment]
I see, I just tried resubscribing `withRuntime=false` again after getting the `stop` notification (after wrap sync) and then it does receive the same events as a `withRuntime=true` subscription.

I understand that after wrap sync, if there's a new block with a new runtime, `withRuntime=false` subscription will receive it immediately, whereas `withRuntime=true` will wait until the runtime spec was loaded.

Thank you!
