### ISSUE TITLE
Replace Deprecated usize Methods with associated "MIN" and "MAX" Constants

### ISSUE THREAD

**Issue by fewForce** [smol-dot/smoldot#1679]
Noticed that the codebase uses the `usize::min_value()` and `usize::max_value()` methods, which are deprecated and slated for future removal. The Rust documentation recommends using the associated constants `usize::MIN` and `usize::MAX` as replacements.

### Issue Description:
The use of deprecated methods can lead to warnings during compilation and may affect the forward compatibility of the project with future versions of Rust. Transitioning to the recommended constants ensures compliance with the latest Rust standards and practices.

### Proposed Changes:
Replacing all instances of `usize::min_value()` with `usize::MIN` and `usize::max_value()` with `usize::MAX` across the entire `smoldot` codebase. This change will not only eliminate deprecation warnings but also align the project with the latest Rust idioms.

### Affected Files:
The deprecation impacts several files across the project. Our examination revealed approximately 141 occurrences of usize::max_value() and 52 occurrences of usize::min_value() across various files in the project. These deprecated methods are spread throughout the codebase, indicating a wide-reaching impact on several modules and components.

### Next Steps:
Willing to assist in this transition and can contribute by submitting a pull request with the necessary changes. Before proceeding, I wanted to discuss this with the team to ensure alignment and gather any additional input you might have.

**Comment by tomaka** [comment]
Indeed, they should be replaced with `MIN` and `MAX`. This doesn't concern just `usize` but all integer types.

However, since this is a very easy change (just a search and replace) but that it would be extremely annoying to review a PR that does that, and that the change would conflict with some big PRs I have on the way, I would prefer to do this myself if you don't mind.

**Comment by fewForce** [comment]
I do respect the fact that you do reached out to me & explained the reasoning behind your thought.

My motivation for submitting the change was : 
a) Upon examining the code, I noticed a prevailing convention in the industry favoring constants over methods, which has been further reinforced by the Rust Foundation's adoption to align with these industry standards. I fully recognize that as the core maintainer, you have better visibility into the trajectory of Smoldot's development.

b) I would like to highlight a concern: Given that this change represents a low-hanging fruit in terms of implementation, complexity and primarily aims at aligning with industry standards, there's a risk that it may be deprioritized and pushed to later releases.

c) Despite its simplicity, could inadvertently impact a significant portion of developers who rely on open-source projects like Smoldot for educational purposes.

I am open to any decision you make on this matter, as both paths have their merits.Thank you for considering my input, and I look forward to your decision.

**Comment by tomaka** [comment]
I'm glad that you're concerned with industry standards, but turning `min_value()` into `MIN` and `max_value()` into `MAX` is a very small change and is very low priority.

Smoldot has maybe around 100k lines of code right now. These 100k lines of code contain **a lot** of things are not industry standards or aren't great for educational purposes. If I had to create a list, ordered by decreasing importance, this issue would probably be around position 50.

It is the reality of software engineering that no code is ever perfect. This issue is amongst issues that would turn "very high quality" code into "extraordinary quality" code. Smoldot's code is I think "good quality" but not more, and I don't think I could name a single software project of "very high" quality.
