### ISSUE TITLE
what's the plan about ext_storage_proof_size_storage_proof_size_version_1?

### ISSUE THREAD

**Issue by xlc** [smol-dot/smoldot#1833]
https://github.com/AcalaNetwork/chopsticks/issues/754

not sure if there is already an issue about it but looks like more teams are using this feature

**Comment by tomaka** [comment]
Well, I was vehemently against [RFC 43](https://github.com/polkadot-fellows/RFCs/pull/43).

In the discussion, I explained that in my opinion this function isn't implementable because generating a proof is currently an implementation detail. @bkchr and @skunert on the other hand claim that they could properly write a spec of how proof generation works should work deterministically. If such a spec appears, I can implement it, otherwise I won't.

**Comment by bkchr** [comment]
You can just provide the host function and return 0.

**Comment by tomaka** [comment]
I went with the solution of tossing the hot potato to the API user.
