### ISSUE TITLE
Plan to replace async-std with tokio?

### ISSUE THREAD

**Issue by koushiro** [smol-dot/smoldot#354]
Does smoldot has a plan to replace `async-std` with `tokio`?

**Comment by tomaka** [comment]
No

**Comment by tomaka** [comment]
The longer answer is that `tokio` only has drawbacks compared to `async-std`, and I don't understand why people keep wanting to use `tokio`.
`tokio` might be very slightly faster (in theory, because I have personally measured in the past and was unable to find a difference), but in a situation where you have 10 connections it really really doesn't matter the slightest.

To me, switching to `tokio` isn't a rational decision. It's driven by the sensation that `tokio` looks more professional.

If you give me rational arguments why we should switch to `tokio` I would consider it, but be aware that this tokio vs async-std debate happened many times before and I'm ready to counter-argue.

**Comment by koushiro** [comment]
I know there's been a lot of discussion about whether to use `tokio` or `async-std` in the rust community, and your reply also makes sense to me.

I'm asking this question for two reasons: one is that I want to introduce `smoldot` into my project, but I don't want too many dependencies in my project (which already relies heavily on `tokio`), and the second is that `tokio` is more actively maintained than `async-std`, even though the current version of `async-std` is sufficient for us.

**Comment by tomaka** [comment]
> I don't want too many dependencies in my project

If what you really want is reduce the number of dependencies, I could just copy-paste the code of `async-std` into smoldot.
I suppose that what you want instead is not bloat the code too much, and `async-std` is fortunately pretty light.

> tokio is more actively maintained than async-std

Yes but `async-std` works perfectly. Requiring no maintenance ought to be a sign of good quality.

**Comment by tomaka** [comment]
Closing since this was a question and the discussion has stalled
