### ISSUE TITLE
WebAssembly.compile(): Compiling function #22 failed: Wasm SIMD unsupporte

### ISSUE THREAD

**Issue by wirednkod** [smol-dot/smoldot#895]
A strange error occurred to one of Burnr wallet users from Substrate-connect repo (https://github.com/paritytech/substrate-connect/issues/1455#issue-1794579396);

The following error appears in his browsers (Brave/Firefox):
On the Firefox console appears the error message:
```
2023-07-07 12:27:53 BURNR-WALLET: Error: CrashError: Error while creating the chain: CompileError: wasm validation error: at offset 16960: unrecognized opcode: fd 0
Wrapper main.js:152690
_createSuperInternal main.js:152687
CrashError types.ts:141
../../packages/connect/dist/mjs/connector/extension.js/createScClient/_callee/_callee$/< extension.ts:97
js
```

And on Brave console appears the message:
```
logger.js:56 2023-07-07 12:16:02 BURNR-WALLET: Error: CrashError: Error while creating the chain: CompileError: WebAssembly.compile(): Compiling function https://github.com/paritytech/substrate-connect/issues/22 failed: Wasm SIMD unsupported @+16960
at extension.ts:97:24
at extension.ts:22:34
```

I was not able to reproduce even after the latest update to `Smoldot 1.0.11`

**Comment by tomaka** [comment]
This shows that the version of Firefox is lower than Firefox v89.
Firefox v89 was released on June 1st 2021.

As for Brave, I don't know the version required, but I imagine that it's old as well.

**Comment by wirednkod** [comment]
Thank you @tomaka - I have already asked for feedback on versions. I will close this once I have it validated

**Comment by tomaka** [comment]
Opcode `fd 0` is indeed a SIMD operation according to https://pengowray.github.io/wasm-ops/#simd

The error messages very clearly say that they are using a version of Firefox and Brave that doesn't support SIMD. For Firefox this is version 88 and below.
Maybe if they've tweaked an option to disable SIMD, or they have multiple versions of the browser installed and using the wrong one, or something like that, but it's a problem on their side.

**Comment by tomaka** [comment]
There's a `javascript.options.wasm_simd_avx` option in `about:config`. They might have disabled it for some reason.

**Comment by juandesouza** [comment]
Hi, the wasm_simd_avx option is enabled on firefox, I just checked.
Both browsers are updated, since their updates come with the linux package manager, that I update every day. I don't have multiple versions of firefox or brave installed. only one version from each, which I maintain updated contantly.
I couldn't run the test from wasm-feature-detect, since I didn't find it was clear how I should run the test. I put the <script> inside an html file and opened the html on a browser, but it didn't work. So I couldn't try it. But at least on firefox the simd_avx option is enabled. On Brave I entered the brave://flags but didn't find anything related to it.

I just tried to open the app on another computer that is here in the house and it opened with Brave, which is funny, since it is a computer that is barely used, it's only used to access Zoom and a few pages once per month. And mine, that is used for programming, it doesn't work. The only difference is that the other is a brand new computer, and mine is a very old one. But relating to software, both are equal, since I installed everything on both equally.

**Comment by wirednkod** [comment]
Since this is not smoldot related issue but rather a computer/software I will close the issue

**Comment by tomaka** [comment]
So far I've been assuming that WASM SIMD instructions are working on every hardware, and that they are emulated if the hardware doesn't support them. After all, that's what makes sense to me given that the goal of WASM is precisely to work on every platform.
I have the impression that wasmtime does support them everywhere, but I don't know for Firefox/Brave, and this type of thing is completely un-googlable.

If WASM SIMD instructions aren't working on every hardware, there are two ways I could solve the problem on smoldot's side: disable SIMD when compiling, or shipping two versions of smoldot (one with and one without SIMD) and detecting at runtime whether SIMD works and thus which one to use.

The second solution would in theory be better, but it would require JavaScript dynamic imports, and I'd rather not use any JavaScript feature that is less than 10 years old because the ecosystem is so fucked up.

**Comment by tomaka** [comment]
The biggest benefitor of SIMD instructions would be ChaCha20 when encrypting the networking communication, but the `chacha20` library doesn't support WASM SIMD instructions anyway, so we're probably not losing much.
